[Umons]
source            = imaps+xoauth2://231026%40umons.ac.be@outlook.office365.com:993
source-cred-cmd   = python3 $HOME/.config/aerc/mutt_oauth2.py $HOME/.config/aerc/231026@umons.ac.be.tokens
outgoing          = smtp+xoauth2://231026%40umons.ac.be@smtp.office365.com:587
outgoing-cred-cmd = python3 $HOME/.config/aerc/mutt_oauth2.py $HOME/.config/aerc/231026@umons.ac.be.tokens
default           = INBOX
cache-headers     = true
archive           = Archives
from              = "Maxime Bartha" <maxime.bartha@student.umons.ac.be>
folders-exclude   = Notes, Journal, ~Calendrier*, Contacts, Flux RSS, Trash, Tâches, ~Problèmes*, Historique des conversations, Boîte d'envoi
# carddav-source    = https://Maxime@calendar.barathaba.be/dav.php/addressbooks/Maxime/default/
# carddav-source-cred-cmd = pass joselin/baikalPerso
# address-book-cmd  = carddav-query -S Umons %s

[Zurich]
source            = imaps+xoauth2://mbartha%40student.ethz.ch@outlook.office365.com:993
source-cred-cmd   = python3 $HOME/.config/aerc/mutt_oauth2.py $HOME/.config/aerc/mbartha@student.ethz.ch.tokens
outgoing          = smtp+xoauth2://mbartha%40ethz.ch@smtp.office365.com:587
outgoing-cred-cmd = python3 $HOME/.config/aerc/mutt_oauth2.py $HOME/.config/aerc/mbartha@student.ethz.ch.tokens
default           = INBOX
cache-headers     = true
archive           = Archives
from              = "Maxime Bartha" <mbartha@student.ethz.ch>
folders-exclude   = Notes, Journal, ~Calendar*, Contacts, Trash, Tasks, Conversation History
