#!/bin/bash
# displaybrightness.sh

brightness=$(cat /sys/class/backlight/intel_backlight/brightness)
max=$(cat /sys/class/backlight/intel_backlight/max_brightness)

percentage=$((brightness*100/max))

brightness_icon=""

dunstify -t 1000 -h string:x-dunst-stack-tag:brightness_notif -h int:value:$percentage "$brightness_icon $percentage%"
